### ISSUE TITLE
Can't distinguish fuel and convenience 

### ISSUE THREAD

**Issue by jleedev** [iandees/poism-py#21]
7-Eleven (among others) are identical in name and logo and this site doesn't tell me whether I've selected the amenity=fuel one or the shop=convenience one.

![Screenshot_20230511-155839](https://github.com/iandees/poism-py/assets/23022/dba63f6f-8a98-4662-98e3-3c8de9cdcd12)

**Comment by iandees** [comment]
Oh interesting. I'll have to look into a way of disambiguating those, thanks for pointing it out.

**Comment by iandees** [comment]
In iD, there is disambiguation through the subtext below the name:

<img width="373" alt="image" src="https://github.com/iandees/poism-py/assets/261584/ba3ec083-ce44-4011-936b-9b6217dd8479">

@bhousel, can you help me figure out how iD gets those out of the preset JSON?

**Comment by bhousel** [comment]
> @bhousel, can you help me figure out how iD gets those out of the preset JSON?

Sure, it looks like that part of the code calls this second line a "subtitle"
For the NSI presets, this code computes the subtitle by just popping off the end of the presetID and sends the rest of it through the localization system:

https://github.com/openstreetmap/iD/blob/bd98ff904bb9498ae60fd32548cd2bbcf244bb53/modules/presets/preset.js#L126-L142

So from here:
https://github.com/osmlab/name-suggestion-index/blob/main/dist/presets/nsi-id-presets.json

You will get a preset like:

```js
   "amenity/fuel/7eleven-d19133": {
      "name": "7-Eleven",
      "locationSet": {"include": ["001"], "exclude": ["no", "pl"]},
      "icon": "maki-fuel",
      "geometry": ["point", "area"],
      "matchScore": 2,
      "imageURL": "https://graph.facebook.com/7ElevenMexico/picture?type=large",
      "terms": ["7-11", "7-eleven", "seven eleven"],
      "fields": ["name", "brand", "{amenity/fuel}"],
      "tags": {"amenity": "fuel", "brand:wikidata": "Q259340"},
      "addTags": {
        "amenity": "fuel",
        "brand": "7-Eleven",
        "brand:wikidata": "Q259340",
        "name": "7-Eleven"
      }
    },
```

The id is: `amenity/fuel/7eleven-d19133` 
The name is "7-Eleven" 
The subtitle is whatever name you get from the iD preset `amenity/fuel` which is "Gas Station"

The iD presets are localized, I think you probably already fetch them for poism?, but the strings are in a file like this:
https://github.com/openstreetmap/id-tagging-schema/blob/a9d966d53eada73d60ae08880ce5c9e38c5e5797/dist/translations/en.json#L8990-L8992

**Comment by iandees** [comment]
Thank you!!

**Comment by iandees** [comment]
I added a change in 607b110 that does the subtitle calculation. I also added the icons to the autocomplete:

<img width="735" alt="image" src="https://github.com/iandees/poism-py/assets/261584/ede3d75b-f5f6-4078-899a-5b3c10ac55b9">

**Comment by jleedev** [comment]
Nice! I should note that the edit page also needs to support this.

**Comment by iandees** [comment]
Good reminder. I did that in 7f48bf2.
